trigger:
  batch: true
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

parameters:
  - name: dotnet_configurations
    type: object
    default:
      - Release
  - name: buildPlatforms
    type: object
    default:
      - x64
      - arm64

#     0.0.yyMM.dd##
#     0.0.1904.0900
name: 0.0.$(Date:yyMM).$(Date:dd)$(Rev:rr)

jobs:
- job: BuildNuGet
  displayName: Build Nuget and Run Tests
  strategy:
    matrix:
      ${{ each dotnet_config in parameters.dotnet_configurations }}:
        Windows_${{ dotnet_config }}:
          os: windows-latest
          dotnet_configuration: ${{ dotnet_config }}
        Linux_${{ dotnet_config }}:
          os: ubuntu-latest
          dotnet_configuration: ${{ dotnet_config }}
        Mac_${{ dotnet_config }}:
          os: macos-latest
          dotnet_configuration: ${{ dotnet_config }}
  pool:
    vmImage: $(os)
  steps:
  - checkout: self
  - task: UseDotNet@2
    displayName: Setup .NET
    inputs:
      version: 6.0.x
  - script: dotnet restore MSStore.CLI.sln /p:Configuration=$(dotnet_configuration)
    displayName: Restore dependencies
  - template: ../templates/build-nuget.yaml
    parameters:
      dotnet_configuration: $(dotnet_configuration)
      AgentOS: $(Agent.OS)

- job: BuildCLI
  displayName: Build CLI
  strategy:
    matrix:
      ${{ each dotnet_config in parameters.dotnet_configurations }}:
        ${{ each platform in parameters.buildPlatforms }}:
          ${{ dotnet_config }}_windows_${{ platform }}:
            os: windows-latest
            dotnet_runtime: win
            dotnet_framework: net6.0-windows10.0.17763.0
            dotnet_arch: ${{ platform }}
            dotnet_configuration: ${{ dotnet_config }}
          ${{ dotnet_config }}_linux_${{ platform }}:
            os: ubuntu-latest
            dotnet_runtime: linux
            dotnet_framework: net6.0
            dotnet_arch: ${{ platform }}
            dotnet_configuration: ${{ dotnet_config }}
          ${{ dotnet_config }}_macos_${{ platform }}:
            os: macos-latest
            dotnet_runtime: osx.12
            dotnet_framework: net6.0
            dotnet_arch: ${{ platform }}
            dotnet_configuration: ${{ dotnet_config }}
  pool:
    vmImage: $(os)
  steps:
  - checkout: self
  - task: UseDotNet@2
    displayName: Setup .NET
    inputs:
      version: 6.0.x
  - script: dotnet restore MSStore.CLI -r $(dotnet_runtime)-$(dotnet_arch) /p:Configuration=$(dotnet_configuration)
    displayName: Restore CLI
  - template: ../templates/build-cli.yaml
    parameters:
      dotnet_runtime: $(dotnet_runtime)
      dotnet_framework: $(dotnet_framework)
      dotnet_arch: $(dotnet_arch)